name: Test docker image
on:
  push:
    # Runs on pushes targeting the default branch
    branches: [main]

jobs:
  docker-job:
    runs-on: self-hosted
    container:
      image: python:3.11  # Replace with your desired Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Python version
        run: python --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt